#端口
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-connections: 50000
    ## 最大工作线程数，默认200。（4核8g内存，线程数经验值800，操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。)
    max-threads: 5000
    ## 等待队列长度，默认100。
    accept-count: 10000
    ## 最小工作空闲线程数，默认10。（适当增大一些，以便应对突然增长的访问量）
    min-spare-threads: 1000
#spring的配置
spring:
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.224.175:8066/TESTDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #注入数据源的类型   默认的为HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        #        login-username: root
        #        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true  #启用数据源监控
  # rabbitmq配置
  rabbitmq:
    host: 101.200.224.175
    port: 5672
    username: pochi
    password: 123456
    virtual-host: /pochi-pay
    publisher-confirm-type: correlated #开启消息到达交互机的确认机制
    publisher-returns: true #消息由交互机到达队列时失败触发
    listener:
      simple:
        acknowledge-mode: manual #手动签收
        #acknowledge-mode: auto #自动签收 这个是默认行为
      direct:
        acknowledge-mode: manual #设置直连交互机的签收类型
  #配置redis就集群
  redis:
    timeout: 6000ms
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 101.200.224.175:7000
        - 101.200.224.175:7001
        - 101.200.224.175:7002
        - 101.200.224.175:7003
        - 101.200.224.175:7004
        - 101.200.224.175:7005
    jedis:
      pool:
        max-active: 10000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 1000 # 连接池中的最大空闲连接
        min-idle: 50 # 连接池中的最小空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      port: 6390
#      host: 101.200.224.175
#      password: 123456
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      host: 101.200.224.175
      port: 27017
      database: pochi

#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
#fastdfs的配置
fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 600   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - 101.200.224.175:22122
upload:
  base-url: http://101.200.224.175/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
#dubbo配置
dubbo:
  application:
    name: pochi-system-web-service
  registry:
    address: zookeeper://101.200.224.175:2181
  consumer:
    check: false
    threads: 100000
  protocol:
    threads: 100000
  provider:
    threads: 100000
# 微信配置
wechat:
  appId: wx4b5bbd6a89d564c7
  appSecret: 1ab4c3a3efb63826e768fe45fad882ce
  grantType: authorization_code
  loginUrl: https://api.weixin.qq.com/sns/jscode2session?grant_type=authorization_code&
  accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&
  pushUrl: https://api.weixin.qq.com/cgi-bin/message/subscribe/send?access_token=