#端口
server:
  port: 8080
#spring的配置
spring:
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pochi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    #注入数据源的类型   默认的为HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        #        login-username: root
        #        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true  #启用数据源监控
  #配置redis
  redis:
    port: 6390
    host: 39.101.131.194
    password: 123456
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      host: 39.101.131.194
      port: 27017
      database: pochi

#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
#fastdfs的配置
fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 600   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - 39.101.131.194:22122
upload:
  base-url: http://39.101.131.194:8888
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
#dubbo配置
dubbo:
  application:
    name: pochi-system-web-service
  registry:
    address: zookeeper://39.101.131.194:2181
  consumer:
    check: false
  protocol:
    threads: 100000
# 微信配置
wechat:
  appId: wx4b5bbd6a89d564c7
  appSecret: 1ab4c3a3efb63826e768fe45fad882ce
  grantType: authorization_code
  loginUrl: https://api.weixin.qq.com/sns/jscode2session